/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AirAvatar {
        "bgColor": string;
        "name": string;
        "rounded": boolean;
        "size": string;
    }
    interface AirButton {
        "autoWidth": boolean;
        "circle": boolean;
        "content": string;
        "disabled": boolean;
        "ghost": boolean;
        "icon": string;
        "loading": boolean;
        "plain": boolean;
        "round": boolean;
        "size": 'big' | 'small' | 'medium';
        "suffixIcon": string;
        "type": 'primary' | 'success' | 'info' | 'warning' | 'danger' | '';
    }
    interface AirCard {
        "description": string;
        "imageUrl": string;
        "showButton": boolean;
        "tags": string[];
        "title": string;
    }
    interface AirRow {
    }
    interface DemoSection {
    }
    interface FooterNav {
    }
    interface HeroSection {
    }
    interface MainApp {
    }
    interface TopNavBar {
    }
}
declare global {
    interface HTMLAirAvatarElement extends Components.AirAvatar, HTMLStencilElement {
    }
    var HTMLAirAvatarElement: {
        prototype: HTMLAirAvatarElement;
        new (): HTMLAirAvatarElement;
    };
    interface HTMLAirButtonElement extends Components.AirButton, HTMLStencilElement {
    }
    var HTMLAirButtonElement: {
        prototype: HTMLAirButtonElement;
        new (): HTMLAirButtonElement;
    };
    interface HTMLAirCardElement extends Components.AirCard, HTMLStencilElement {
    }
    var HTMLAirCardElement: {
        prototype: HTMLAirCardElement;
        new (): HTMLAirCardElement;
    };
    interface HTMLAirRowElement extends Components.AirRow, HTMLStencilElement {
    }
    var HTMLAirRowElement: {
        prototype: HTMLAirRowElement;
        new (): HTMLAirRowElement;
    };
    interface HTMLDemoSectionElement extends Components.DemoSection, HTMLStencilElement {
    }
    var HTMLDemoSectionElement: {
        prototype: HTMLDemoSectionElement;
        new (): HTMLDemoSectionElement;
    };
    interface HTMLFooterNavElement extends Components.FooterNav, HTMLStencilElement {
    }
    var HTMLFooterNavElement: {
        prototype: HTMLFooterNavElement;
        new (): HTMLFooterNavElement;
    };
    interface HTMLHeroSectionElement extends Components.HeroSection, HTMLStencilElement {
    }
    var HTMLHeroSectionElement: {
        prototype: HTMLHeroSectionElement;
        new (): HTMLHeroSectionElement;
    };
    interface HTMLMainAppElement extends Components.MainApp, HTMLStencilElement {
    }
    var HTMLMainAppElement: {
        prototype: HTMLMainAppElement;
        new (): HTMLMainAppElement;
    };
    interface HTMLTopNavBarElement extends Components.TopNavBar, HTMLStencilElement {
    }
    var HTMLTopNavBarElement: {
        prototype: HTMLTopNavBarElement;
        new (): HTMLTopNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "air-avatar": HTMLAirAvatarElement;
        "air-button": HTMLAirButtonElement;
        "air-card": HTMLAirCardElement;
        "air-row": HTMLAirRowElement;
        "demo-section": HTMLDemoSectionElement;
        "footer-nav": HTMLFooterNavElement;
        "hero-section": HTMLHeroSectionElement;
        "main-app": HTMLMainAppElement;
        "top-nav-bar": HTMLTopNavBarElement;
    }
}
declare namespace LocalJSX {
    interface AirAvatar {
        "bgColor"?: string;
        "name"?: string;
        "rounded"?: boolean;
        "size"?: string;
    }
    interface AirButton {
        "autoWidth"?: boolean;
        "circle"?: boolean;
        "content"?: string;
        "disabled"?: boolean;
        "ghost"?: boolean;
        "icon"?: string;
        "loading"?: boolean;
        "plain"?: boolean;
        "round"?: boolean;
        "size"?: 'big' | 'small' | 'medium';
        "suffixIcon"?: string;
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger' | '';
    }
    interface AirCard {
        "description"?: string;
        "imageUrl"?: string;
        "showButton"?: boolean;
        "tags"?: string[];
        "title"?: string;
    }
    interface AirRow {
    }
    interface DemoSection {
    }
    interface FooterNav {
    }
    interface HeroSection {
    }
    interface MainApp {
    }
    interface TopNavBar {
    }
    interface IntrinsicElements {
        "air-avatar": AirAvatar;
        "air-button": AirButton;
        "air-card": AirCard;
        "air-row": AirRow;
        "demo-section": DemoSection;
        "footer-nav": FooterNav;
        "hero-section": HeroSection;
        "main-app": MainApp;
        "top-nav-bar": TopNavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "air-avatar": LocalJSX.AirAvatar & JSXBase.HTMLAttributes<HTMLAirAvatarElement>;
            "air-button": LocalJSX.AirButton & JSXBase.HTMLAttributes<HTMLAirButtonElement>;
            "air-card": LocalJSX.AirCard & JSXBase.HTMLAttributes<HTMLAirCardElement>;
            "air-row": LocalJSX.AirRow & JSXBase.HTMLAttributes<HTMLAirRowElement>;
            "demo-section": LocalJSX.DemoSection & JSXBase.HTMLAttributes<HTMLDemoSectionElement>;
            "footer-nav": LocalJSX.FooterNav & JSXBase.HTMLAttributes<HTMLFooterNavElement>;
            "hero-section": LocalJSX.HeroSection & JSXBase.HTMLAttributes<HTMLHeroSectionElement>;
            "main-app": LocalJSX.MainApp & JSXBase.HTMLAttributes<HTMLMainAppElement>;
            "top-nav-bar": LocalJSX.TopNavBar & JSXBase.HTMLAttributes<HTMLTopNavBarElement>;
        }
    }
}
